//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES_WEB_ACC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_VoucherDetail
    {
        public long Id { get; set; }
        public Nullable<long> DocId { get; set; }
        public Nullable<int> Linage { get; set; }
        public Nullable<long> AccNoId { get; set; }
        public string AccNo { get; set; }
        public string AccNameC { get; set; }
        public string AccNameE { get; set; }
        public string Remark { get; set; }
        public string DCTypeNo { get; set; }
        public string DCTypeNameC { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> Money1 { get; set; }
        public Nullable<decimal> Money2 { get; set; }
        public Nullable<long> AccProfitId { get; set; }
        public string AccProfitNo { get; set; }
        public string AccProfitName { get; set; }
        public Nullable<long> AccDeptId { get; set; }
        public string AccDeptNo { get; set; }
        public string AccDeptName { get; set; }
        public Nullable<long> PayDeptId { get; set; }
        public string PayDeptNo { get; set; }
        public string PayDeptName { get; set; }
        public Nullable<long> TargetType { get; set; }
        public Nullable<long> TargetId { get; set; }
        public string TargetNo { get; set; }
        public string TargetAbbr { get; set; }
        public string OffsetNo { get; set; }
        public Nullable<long> CaseBillId { get; set; }
        public string CaseBillNo { get; set; }
        public Nullable<long> SourceProjectId { get; set; }
        public string SourceDocSubType { get; set; }
        public string SourceDocSubTypeName { get; set; }
        public Nullable<long> SourceDocId { get; set; }
        public Nullable<long> SourceSeqId { get; set; }
        public string SourceNo { get; set; }
        public Nullable<long> InitialProjectId { get; set; }
        public string InitialDocSubType { get; set; }
        public string InitialDocSubTypeName { get; set; }
        public Nullable<long> InitialDocId { get; set; }
        public string InitialNo { get; set; }
        public Nullable<long> CheckType { get; set; }
        public Nullable<long> CheckId { get; set; }
        public string CheckNo { get; set; }
        public string EventType { get; set; }
        public string ActivityType { get; set; }
        public Nullable<bool> IsParty { get; set; }
        public Nullable<int> BillAddType { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<bool> IsState { get; set; }
        public Nullable<System.DateTime> StateDate { get; set; }
        public string StateBy { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> ShowPage { get; set; }
    }
}
