//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES_WEB_ACC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_VoucherInfo
    {
        public string Id { get; set; }
        public Nullable<long> CompId { get; set; }
        public string CompNo { get; set; }
        public string CompAbbr { get; set; }
        public Nullable<long> AccountBill { get; set; }
        public string DocType { get; set; }
        public string DocSubType { get; set; }
        public string DocSubTypeName { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Code1 { get; set; }
        public string Code2 { get; set; }
        public string BillNo { get; set; }
        public string DcType { get; set; }
        public string VoucherType { get; set; }
        public string VoucherNameC { get; set; }
        public Nullable<long> EmpId { get; set; }
        public string EmpNo { get; set; }
        public string EmpNameC { get; set; }
        public Nullable<long> DeptId { get; set; }
        public string DeptNo { get; set; }
        public string DeptName { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<long> SourceCompId { get; set; }
        public Nullable<long> SourceProjectId { get; set; }
        public string SourceDocSubType { get; set; }
        public string SourceDocSubTypeName { get; set; }
        public Nullable<long> SourceDocId { get; set; }
        public string SourceNo { get; set; }
        public Nullable<int> BillAddType { get; set; }
        public string Remark { get; set; }
        public string ActivityType { get; set; }
        public string AccDocType { get; set; }
        public Nullable<decimal> Money11 { get; set; }
        public Nullable<decimal> Money12 { get; set; }
        public Nullable<decimal> Money21 { get; set; }
        public Nullable<decimal> Money22 { get; set; }
        public Nullable<decimal> Money1Dc { get; set; }
        public Nullable<decimal> Money2Dc { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<bool> IsState { get; set; }
        public Nullable<System.DateTime> StateDate { get; set; }
        public string StateBy { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> BillStatus { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string SignBy { get; set; }
    }
}
