//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES_WEB_ACC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NES_WEB_ACCEntities : DbContext
    {
        public NES_WEB_ACCEntities()
            : base("name=NES_WEB_ACCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LNK_RolePermissions> LNK_RolePermissions { get; set; }
        public virtual DbSet<LNK_UserRole> LNK_UserRole { get; set; }
        public virtual DbSet<SYS_Permissions> SYS_Permissions { get; set; }
        public virtual DbSet<SYS_Roles> SYS_Roles { get; set; }
        public virtual DbSet<SYS_Users> SYS_Users { get; set; }
        public virtual DbSet<ACC_AccCode1> ACC_AccCode1 { get; set; }
        public virtual DbSet<ACC_AccCode2> ACC_AccCode2 { get; set; }
        public virtual DbSet<ACC_AccTitleNo> ACC_AccTitleNo { get; set; }
        public virtual DbSet<ACC_EquityInfo> ACC_EquityInfo { get; set; }
        public virtual DbSet<ACC_EquityItem> ACC_EquityItem { get; set; }
        public virtual DbSet<ACC_SysDocSubType> ACC_SysDocSubType { get; set; }
        public virtual DbSet<ACC_VoucherKind> ACC_VoucherKind { get; set; }
        public virtual DbSet<ACC_DataSet> ACC_DataSet { get; set; }
        public virtual DbSet<ACC_AccTitleNo_MX> ACC_AccTitleNo_MX { get; set; }
        public virtual DbSet<ACC_VoucherDetail> ACC_VoucherDetail { get; set; }
        public virtual DbSet<ACC_VoucherInfo> ACC_VoucherInfo { get; set; }
        public virtual DbSet<ACC_Rate> ACC_Rate { get; set; }
    }
}
