//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES_WEB_ACC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDocSubType
    {
        public long Id { get; set; }
        public Nullable<long> DocId { get; set; }
        public string Code { get; set; }
        public string CodeNameC { get; set; }
        public string CodeNameE { get; set; }
        public string CaptionC { get; set; }
        public string CaptionE { get; set; }
        public string IsoNo { get; set; }
        public string Bpm { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<bool> IsState { get; set; }
        public Nullable<System.DateTime> StateDate { get; set; }
        public string StateBy { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<bool> IsAR { get; set; }
        public Nullable<bool> IsMessage { get; set; }
        public Nullable<bool> IsMail { get; set; }
        public Nullable<bool> IsApp { get; set; }
        public Nullable<bool> IsOther { get; set; }
        public string WhKind { get; set; }
        public string ProdProperty { get; set; }
        public Nullable<bool> IsMessage2 { get; set; }
        public Nullable<bool> IsMessage3 { get; set; }
        public Nullable<bool> IsMail2 { get; set; }
        public Nullable<bool> IsMail3 { get; set; }
    }
}
