//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES_WEB_ACC.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NES_WEB_ACC.App_GlobalResources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Code 的當地語系化字串。
        /// </summary>
        public static string AccCode {
            get {
                return ResourceManager.GetString("AccCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccCodeSet 的當地語系化字串。
        /// </summary>
        public static string AccCodeSet {
            get {
                return ResourceManager.GetString("AccCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Group Name 的當地語系化字串。
        /// </summary>
        public static string AccGroupNameC {
            get {
                return ResourceManager.GetString("AccGroupNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Group NameE 的當地語系化字串。
        /// </summary>
        public static string AccGroupNameE {
            get {
                return ResourceManager.GetString("AccGroupNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Group No 的當地語系化字串。
        /// </summary>
        public static string AccGroupNo {
            get {
                return ResourceManager.GetString("AccGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccGroupNoSet 的當地語系化字串。
        /// </summary>
        public static string AccGroupNoSet {
            get {
                return ResourceManager.GetString("AccGroupNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Name 的當地語系化字串。
        /// </summary>
        public static string AccNameC {
            get {
                return ResourceManager.GetString("AccNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No 的當地語系化字串。
        /// </summary>
        public static string AccNo {
            get {
                return ResourceManager.GetString("AccNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No By 的當地語系化字串。
        /// </summary>
        public static string AccNoBy {
            get {
                return ResourceManager.GetString("AccNoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No By Name 的當地語系化字串。
        /// </summary>
        public static string AccNoByNameC {
            get {
                return ResourceManager.GetString("AccNoByNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No Type 的當地語系化字串。
        /// </summary>
        public static string AccNoType {
            get {
                return ResourceManager.GetString("AccNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccReport 的當地語系化字串。
        /// </summary>
        public static string AccReport {
            get {
                return ResourceManager.GetString("AccReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccSet 的當地語系化字串。
        /// </summary>
        public static string AccSet {
            get {
                return ResourceManager.GetString("AccSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccSysCodeSet 的當地語系化字串。
        /// </summary>
        public static string AccSysCodeSet {
            get {
                return ResourceManager.GetString("AccSysCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AJE 的當地語系化字串。
        /// </summary>
        public static string AJE {
            get {
                return ResourceManager.GetString("AJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BillDate 的當地語系化字串。
        /// </summary>
        public static string BillDate {
            get {
                return ResourceManager.GetString("BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BillNo 的當地語系化字串。
        /// </summary>
        public static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompAbbr 的當地語系化字串。
        /// </summary>
        public static string CompAbbr {
            get {
                return ResourceManager.GetString("CompAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompNo 的當地語系化字串。
        /// </summary>
        public static string CompNo {
            get {
                return ResourceManager.GetString("CompNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DC Type Name 的當地語系化字串。
        /// </summary>
        public static string DCTypeNameC {
            get {
                return ResourceManager.GetString("DCTypeNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DC Type No 的當地語系化字串。
        /// </summary>
        public static string DCTypeNo {
            get {
                return ResourceManager.GetString("DCTypeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EmpNameC 的當地語系化字串。
        /// </summary>
        public static string EmpNameC {
            get {
                return ResourceManager.GetString("EmpNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EmpNo 的當地語系化字串。
        /// </summary>
        public static string EmpNo {
            get {
                return ResourceManager.GetString("EmpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquityCodeSet 的當地語系化字串。
        /// </summary>
        public static string EquityCodeSet {
            get {
                return ResourceManager.GetString("EquityCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finance Report 的當地語系化字串。
        /// </summary>
        public static string FinanceReport {
            get {
                return ResourceManager.GetString("FinanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Work Flow 的當地語系化字串。
        /// </summary>
        public static string FlowChart {
            get {
                return ResourceManager.GetString("FlowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Instrument 的當地語系化字串。
        /// </summary>
        public static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Control 的當地語系化字串。
        /// </summary>
        public static string IsControl {
            get {
                return ResourceManager.GetString("IsControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string lblMenuLanguage {
            get {
                return ResourceManager.GetString("lblMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission Setting 的當地語系化字串。
        /// </summary>
        public static string lblPermissionSetting {
            get {
                return ResourceManager.GetString("lblPermissionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remark 的當地語系化字串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SystemManagement-Roles 的當地語系化字串。
        /// </summary>
        public static string SystemManagementRoles {
            get {
                return ResourceManager.GetString("SystemManagementRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SystemManagement-Users 的當地語系化字串。
        /// </summary>
        public static string SystemManagementUsers {
            get {
                return ResourceManager.GetString("SystemManagementUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VoucherCodeSet 的當地語系化字串。
        /// </summary>
        public static string VoucherCodeSet {
            get {
                return ResourceManager.GetString("VoucherCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Create 的當地語系化字串。
        /// </summary>
        public static string VoucherCreate {
            get {
                return ResourceManager.GetString("VoucherCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VoucherNameC 的當地語系化字串。
        /// </summary>
        public static string VoucherNameC {
            get {
                return ResourceManager.GetString("VoucherNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Operation 的當地語系化字串。
        /// </summary>
        public static string VoucherOperation {
            get {
                return ResourceManager.GetString("VoucherOperation", resourceCulture);
            }
        }
    }
}
