//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES_WEB_ACC.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NES_WEB_ACC.App_GlobalResources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Accounting amount 的當地語系化字串。
        /// </summary>
        public static string Aamount {
            get {
                return ResourceManager.GetString("Aamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Account book type 的當地語系化字串。
        /// </summary>
        public static string AccBookType {
            get {
                return ResourceManager.GetString("AccBookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Code 的當地語系化字串。
        /// </summary>
        public static string AccCode {
            get {
                return ResourceManager.GetString("AccCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccCodeSet 的當地語系化字串。
        /// </summary>
        public static string AccCodeSet {
            get {
                return ResourceManager.GetString("AccCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cost center name 的當地語系化字串。
        /// </summary>
        public static string AccDeptName {
            get {
                return ResourceManager.GetString("AccDeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cost center No 的當地語系化字串。
        /// </summary>
        public static string AccDeptNo {
            get {
                return ResourceManager.GetString("AccDeptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Group Name 的當地語系化字串。
        /// </summary>
        public static string AccGroupNameC {
            get {
                return ResourceManager.GetString("AccGroupNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Group NameE 的當地語系化字串。
        /// </summary>
        public static string AccGroupNameE {
            get {
                return ResourceManager.GetString("AccGroupNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc Group No 的當地語系化字串。
        /// </summary>
        public static string AccGroupNo {
            get {
                return ResourceManager.GetString("AccGroupNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccGroupNoSet 的當地語系化字串。
        /// </summary>
        public static string AccGroupNoSet {
            get {
                return ResourceManager.GetString("AccGroupNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ACC Name 的當地語系化字串。
        /// </summary>
        public static string AccName {
            get {
                return ResourceManager.GetString("AccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ACC Name (Chinese) 的當地語系化字串。
        /// </summary>
        public static string AccNameC {
            get {
                return ResourceManager.GetString("AccNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ACC Name (English) 的當地語系化字串。
        /// </summary>
        public static string AccNameE {
            get {
                return ResourceManager.GetString("AccNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ACC name (Spanish) 的當地語系化字串。
        /// </summary>
        public static string AccNameMX {
            get {
                return ResourceManager.GetString("AccNameMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No 的當地語系化字串。
        /// </summary>
        public static string AccNo {
            get {
                return ResourceManager.GetString("AccNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No By 的當地語系化字串。
        /// </summary>
        public static string AccNoBy {
            get {
                return ResourceManager.GetString("AccNoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No By Name 的當地語系化字串。
        /// </summary>
        public static string AccNoByNameC {
            get {
                return ResourceManager.GetString("AccNoByNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Acc No Type 的當地語系化字串。
        /// </summary>
        public static string AccNoType {
            get {
                return ResourceManager.GetString("AccNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Accounting department name 的當地語系化字串。
        /// </summary>
        public static string AccProfitName {
            get {
                return ResourceManager.GetString("AccProfitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Accounting department No 的當地語系化字串。
        /// </summary>
        public static string AccProfitNo {
            get {
                return ResourceManager.GetString("AccProfitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccReport 的當地語系化字串。
        /// </summary>
        public static string AccReport {
            get {
                return ResourceManager.GetString("AccReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccSet 的當地語系化字串。
        /// </summary>
        public static string AccSet {
            get {
                return ResourceManager.GetString("AccSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccSysCodeSet 的當地語系化字串。
        /// </summary>
        public static string AccSysCodeSet {
            get {
                return ResourceManager.GetString("AccSysCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action 的當地語系化字串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Activity Type 的當地語系化字串。
        /// </summary>
        public static string ActivityType {
            get {
                return ResourceManager.GetString("ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Next 的當地語系化字串。
        /// </summary>
        public static string AddNext {
            get {
                return ResourceManager.GetString("AddNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Previous 的當地語系化字串。
        /// </summary>
        public static string AddPrevious {
            get {
                return ResourceManager.GetString("AddPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjustment account 的當地語系化字串。
        /// </summary>
        public static string AdjustmentAccount {
            get {
                return ResourceManager.GetString("AdjustmentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Advanced 的當地語系化字串。
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AJE 的當地語系化字串。
        /// </summary>
        public static string AJE {
            get {
                return ResourceManager.GetString("AJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alert 的當地語系化字串。
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Balance Sheet 的當地語系化字串。
        /// </summary>
        public static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Balance Sheet Account 的當地語系化字串。
        /// </summary>
        public static string BalanceSheetAcc {
            get {
                return ResourceManager.GetString("BalanceSheetAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Date 的當地語系化字串。
        /// </summary>
        public static string BillDate {
            get {
                return ResourceManager.GetString("BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher No 的當地語系化字串。
        /// </summary>
        public static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bill Type 的當地語系化字串。
        /// </summary>
        public static string BillType {
            get {
                return ResourceManager.GetString("BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project No 的當地語系化字串。
        /// </summary>
        public static string CaseBillNo {
            get {
                return ResourceManager.GetString("CaseBillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Check 的當地語系化字串。
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bill No 的當地語系化字串。
        /// </summary>
        public static string CheckNo {
            get {
                return ResourceManager.GetString("CheckNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Closed 的當地語系化字串。
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Comp Abbr 的當地語系化字串。
        /// </summary>
        public static string CompAbbr {
            get {
                return ResourceManager.GetString("CompAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Comp No 的當地語系化字串。
        /// </summary>
        public static string CompNo {
            get {
                return ResourceManager.GetString("CompNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact 的當地語系化字串。
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mexican User 的當地語系化字串。
        /// </summary>
        public static string CoworkMX {
            get {
                return ResourceManager.GetString("CoworkMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taiwan User 的當地語系化字串。
        /// </summary>
        public static string CoworkTW {
            get {
                return ResourceManager.GetString("CoworkTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Currency 的當地語系化字串。
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transaction currency 的當地語系化字串。
        /// </summary>
        public static string CurrencyNo {
            get {
                return ResourceManager.GetString("CurrencyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Accounting currency 的當地語系化字串。
        /// </summary>
        public static string CurrencySt {
            get {
                return ResourceManager.GetString("CurrencySt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DC Type Name 的當地語系化字串。
        /// </summary>
        public static string DCTypeNameC {
            get {
                return ResourceManager.GetString("DCTypeNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DC Type  的當地語系化字串。
        /// </summary>
        public static string DCTypeNo {
            get {
                return ResourceManager.GetString("DCTypeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detail 的當地語系化字串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Difference 的當地語系化字串。
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disable 的當地語系化字串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Accountant Name 的當地語系化字串。
        /// </summary>
        public static string EmpNameC {
            get {
                return ResourceManager.GetString("EmpNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Accountant No 的當地語系化字串。
        /// </summary>
        public static string EmpNo {
            get {
                return ResourceManager.GetString("EmpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable 的當地語系化字串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EquityCodeSet 的當地語系化字串。
        /// </summary>
        public static string EquityCodeSet {
            get {
                return ResourceManager.GetString("EquityCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finance Report 的當地語系化字串。
        /// </summary>
        public static string FinanceReport {
            get {
                return ResourceManager.GetString("FinanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First 的當地語系化字串。
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Beginning /Middle /End  (of month) 的當地語系化字串。
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workflow 的當地語系化字串。
        /// </summary>
        public static string FlowChart {
            get {
                return ResourceManager.GetString("FlowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Income Statement 的當地語系化字串。
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Initial Bill Type 的當地語系化字串。
        /// </summary>
        public static string InitialDocSubTypeName {
            get {
                return ResourceManager.GetString("InitialDocSubTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Initial Bill No 的當地語系化字串。
        /// </summary>
        public static string InitialNo {
            get {
                return ResourceManager.GetString("InitialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dashboard 的當地語系化字串。
        /// </summary>
        public static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Control 的當地語系化字串。
        /// </summary>
        public static string IsControl {
            get {
                return ResourceManager.GetString("IsControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Enable 的當地語系化字串。
        /// </summary>
        public static string IsEnable {
            get {
                return ResourceManager.GetString("IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Journal 的當地語系化字串。
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last 的當地語系化字串。
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string lblMenuLanguage {
            get {
                return ResourceManager.GetString("lblMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission Setting 的當地語系化字串。
        /// </summary>
        public static string lblPermissionSetting {
            get {
                return ResourceManager.GetString("lblPermissionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Leave 的當地語系化字串。
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No 的當地語系化字串。
        /// </summary>
        public static string Linage {
            get {
                return ResourceManager.GetString("Linage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lock 的當地語系化字串。
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logout 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Month 的當地語系化字串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation code error 的當地語系化字串。
        /// </summary>
        public static string MsgActionErr {
            get {
                return ResourceManager.GetString("MsgActionErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to cancel? 的當地語系化字串。
        /// </summary>
        public static string MsgCfmCancel {
            get {
                return ResourceManager.GetString("MsgCfmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The data has not been saved. Do you want to leave? 的當地語系化字串。
        /// </summary>
        public static string MsgCfmLeave {
            get {
                return ResourceManager.GetString("MsgCfmLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to send? 的當地語系化字串。
        /// </summary>
        public static string MsgCfmSend {
            get {
                return ResourceManager.GetString("MsgCfmSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Server Error： 的當地語系化字串。
        /// </summary>
        public static string MsgErrAja {
            get {
                return ResourceManager.GetString("MsgErrAja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occurred, error code: 的當地語系化字串。
        /// </summary>
        public static string MsgErrCode {
            get {
                return ResourceManager.GetString("MsgErrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Debit and credit imbalance. 的當地語系化字串。
        /// </summary>
        public static string MsgErrDc {
            get {
                return ResourceManager.GetString("MsgErrDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please save first! 的當地語系化字串。
        /// </summary>
        public static string MsgErrSaveFirst {
            get {
                return ResourceManager.GetString("MsgErrSaveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select the row to be edited first! 的當地語系化字串。
        /// </summary>
        public static string MsgSelectRow {
            get {
                return ResourceManager.GetString("MsgSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select the row to be delete first! 的當地語系化字串。
        /// </summary>
        public static string MsgSelectRow1 {
            get {
                return ResourceManager.GetString("MsgSelectRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select the row to be delete first! 的當地語系化字串。
        /// </summary>
        public static string MsgSelectRow2 {
            get {
                return ResourceManager.GetString("MsgSelectRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select the row to be fill in first! 的當地語系化字串。
        /// </summary>
        public static string MsgSelectRow3 {
            get {
                return ResourceManager.GetString("MsgSelectRow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully added： 的當地語系化字串。
        /// </summary>
        public static string MsgSes1 {
            get {
                return ResourceManager.GetString("MsgSes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully edited： 的當地語系化字串。
        /// </summary>
        public static string MsgSes2 {
            get {
                return ResourceManager.GetString("MsgSes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully enabled： 的當地語系化字串。
        /// </summary>
        public static string MsgSes3 {
            get {
                return ResourceManager.GetString("MsgSes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully disable： 的當地語系化字串。
        /// </summary>
        public static string MsgSes4 {
            get {
                return ResourceManager.GetString("MsgSes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully sent： 的當地語系化字串。
        /// </summary>
        public static string MsgSes5 {
            get {
                return ResourceManager.GetString("MsgSes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully reject： 的當地語系化字串。
        /// </summary>
        public static string MsgSes6 {
            get {
                return ResourceManager.GetString("MsgSes6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully closed： 的當地語系化字串。
        /// </summary>
        public static string MsgSes7 {
            get {
                return ResourceManager.GetString("MsgSes7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully delete： 的當地語系化字串。
        /// </summary>
        public static string MsgSes8 {
            get {
                return ResourceManager.GetString("MsgSes8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next 的當地語系化字串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Attention, you have been inactive for too long and will be logged out of the system in 1 minute!! 的當地語系化字串。
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset No 的當地語系化字串。
        /// </summary>
        public static string OffsetNo {
            get {
                return ResourceManager.GetString("OffsetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opt in 的當地語系化字串。
        /// </summary>
        public static string OptIn {
            get {
                return ResourceManager.GetString("OptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment department name 的當地語系化字串。
        /// </summary>
        public static string PayDeptName {
            get {
                return ResourceManager.GetString("PayDeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment department No 的當地語系化字串。
        /// </summary>
        public static string PayDeptNo {
            get {
                return ResourceManager.GetString("PayDeptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Previous 的當地語系化字串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prompts 的當地語系化字串。
        /// </summary>
        public static string Prompts {
            get {
                return ResourceManager.GetString("Prompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Query conditions 的當地語系化字串。
        /// </summary>
        public static string QueryConditions {
            get {
                return ResourceManager.GetString("QueryConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rate 的當地語系化字串。
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rate Setting 的當地語系化字串。
        /// </summary>
        public static string RateSet {
            get {
                return ResourceManager.GetString("RateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refresh 的當地語系化字串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reject 的當地語系化字串。
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remark 的當地語系化字串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remove 的當地語系化字串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Report 的當地語系化字串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Source Bill Type 的當地語系化字串。
        /// </summary>
        public static string SourceDocSubTypeName {
            get {
                return ResourceManager.GetString("SourceDocSubTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Source Bill No 的當地語系化字串。
        /// </summary>
        public static string SourceNo {
            get {
                return ResourceManager.GetString("SourceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Submit 的當地語系化字串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subsidiary Ledger 的當地語系化字串。
        /// </summary>
        public static string SubsidiaryLedger {
            get {
                return ResourceManager.GetString("SubsidiaryLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Supervisor 的當地語系化字串。
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sync Data 的當地語系化字串。
        /// </summary>
        public static string SyncData {
            get {
                return ResourceManager.GetString("SyncData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Setting 的當地語系化字串。
        /// </summary>
        public static string SysSetting {
            get {
                return ResourceManager.GetString("SysSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission Setting 的當地語系化字串。
        /// </summary>
        public static string SystemManagementRoles {
            get {
                return ResourceManager.GetString("SystemManagementRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UserAccount Setting 的當地語系化字串。
        /// </summary>
        public static string SystemManagementUsers {
            get {
                return ResourceManager.GetString("SystemManagementUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System operation process 的當地語系化字串。
        /// </summary>
        public static string SysWorkflow {
            get {
                return ResourceManager.GetString("SysWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transaction amount 的當地語系化字串。
        /// </summary>
        public static string Tamount {
            get {
                return ResourceManager.GetString("Tamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target Name 的當地語系化字串。
        /// </summary>
        public static string TargetAbbr {
            get {
                return ResourceManager.GetString("TargetAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target No 的當地語系化字串。
        /// </summary>
        public static string TargetNo {
            get {
                return ResourceManager.GetString("TargetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target type 的當地語系化字串。
        /// </summary>
        public static string TargetType {
            get {
                return ResourceManager.GetString("TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total 的當地語系化字串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Credit 的當地語系化字串。
        /// </summary>
        public static string TotalCredit {
            get {
                return ResourceManager.GetString("TotalCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Debits 的當地語系化字串。
        /// </summary>
        public static string TotalDebits {
            get {
                return ResourceManager.GetString("TotalDebits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unlock 的當地語系化字串。
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Beginning 的當地語系化字串。
        /// </summary>
        public static string VoucherBeginning {
            get {
                return ResourceManager.GetString("VoucherBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Check 的當地語系化字串。
        /// </summary>
        public static string VoucherCheck {
            get {
                return ResourceManager.GetString("VoucherCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Close 的當地語系化字串。
        /// </summary>
        public static string VoucherClose {
            get {
                return ResourceManager.GetString("VoucherClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Code Set 的當地語系化字串。
        /// </summary>
        public static string VoucherCodeSet {
            get {
                return ResourceManager.GetString("VoucherCodeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Create 的當地語系化字串。
        /// </summary>
        public static string VoucherCreate {
            get {
                return ResourceManager.GetString("VoucherCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VoucherNameC 的當地語系化字串。
        /// </summary>
        public static string VoucherNameC {
            get {
                return ResourceManager.GetString("VoucherNameC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher No 的當地語系化字串。
        /// </summary>
        public static string VoucherNo {
            get {
                return ResourceManager.GetString("VoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Operation 的當地語系化字串。
        /// </summary>
        public static string VoucherOperation {
            get {
                return ResourceManager.GetString("VoucherOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Report 的當地語系化字串。
        /// </summary>
        public static string VoucherReport {
            get {
                return ResourceManager.GetString("VoucherReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Review 的當地語系化字串。
        /// </summary>
        public static string VoucherReview {
            get {
                return ResourceManager.GetString("VoucherReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Summary 的當地語系化字串。
        /// </summary>
        public static string VoucherSummary {
            get {
                return ResourceManager.GetString("VoucherSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Type 的當地語系化字串。
        /// </summary>
        public static string VoucherType {
            get {
                return ResourceManager.GetString("VoucherType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Type Name 的當地語系化字串。
        /// </summary>
        public static string VoucherTypeName {
            get {
                return ResourceManager.GetString("VoucherTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voucher Type No 的當地語系化字串。
        /// </summary>
        public static string VoucherTypeNo {
            get {
                return ResourceManager.GetString("VoucherTypeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workflow 的當地語系化字串。
        /// </summary>
        public static string Workflow {
            get {
                return ResourceManager.GetString("Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Year 的當地語系化字串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
